### ISSUE TITLE
ทำหน้าHome โรงแรม(เสร็จแล้ว)

### ISSUE THREAD

**Issue by Captainrock1** [GodDuckBoy/Hotel-Management#12]

**Comment by KanapongAiamtip** [comment]
@Captainrock1 Don't Merged please tell @GodDuckBoy  to see it before Merged on main project

**Comment by GodDuckBoy** [comment]
We will not merge until everyone finished? idk

**Comment by KanapongAiamtip** [comment]
I think we need to remove the new merge captain file 55 because it's unlikely to be in the same direction as the parent file Oh 5555

**Comment by KanapongAiamtip** [comment]
he can't merge
